name: 'Publish to npm'
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup to npm
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: Build
        run: |
          yarn install --frozen-lockfile
      - name: Publish to npm
        run: |
          LATEST=$(npm show unleash-server version)
          TAG=$(node scripts/npm-tag.js $LATEST)
          npm publish --tag ${TAG:-latest}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJSCIPUBLISH }}
